waypoint_follower:
  ros__parameters:
    loop_rate: 20
    stop_on_failure: True
    waypoint_task_executor_plugin: "wait_at_waypoint"
    service_introspection_mode: "disabled"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 0